# Generated by Django 5.2 on 2025-04-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watch_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
