# Generated by Django 5.2 on 2025-04-30 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_text_testimonial_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='author',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
