# Generated by Django 5.2 on 2025-04-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_testimonial_author_testimonial_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='user',
            new_name='author',
        ),
    ]
