# Generated by Django 5.2 on 2025-04-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_user_testimonial_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('debut_year', models.IntegerField()),
                ('special_powers', models.IntegerField()),
                ('cunning', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('technology', models.IntegerField()),
                ('fact_file', models.TextField()),
                ('image', models.ImageField(blank=True, default='200.png', null=True, upload_to='CharacterCard/')),
            ],
        ),
    ]
