# Generated by Django 5.2 on 2025-04-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_charactercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercard',
            name='back_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
