# Generated by Django 5.2 on 2025-04-30 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_charactercard_back_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercard',
            name='title',
            field=models.CharField(default=datetime.datetime(2025, 4, 30, 10, 29, 3, 705010, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
